//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.08 at 09:34:59 AM EST 
//


package com.liconic.binding.sys;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for climate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="climate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="actual" type="{http://com.liconic.sys}actual" minOccurs="0"/>
 *         &lt;element name="stated" type="{http://com.liconic.sys}stated" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "climate", propOrder = {
    "actual",
    "stated"
})
public class Climate {

    @XmlElementRef(name = "actual", namespace = "http://com.liconic.sys", type = JAXBElement.class, required = false)
    protected JAXBElement<Actual> actual;
    @XmlElementRef(name = "stated", namespace = "http://com.liconic.sys", type = JAXBElement.class, required = false)
    protected JAXBElement<Stated> stated;

    /**
     * Gets the value of the actual property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Actual }{@code >}
     *     
     */
    public JAXBElement<Actual> getActual() {
        return actual;
    }

    /**
     * Sets the value of the actual property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Actual }{@code >}
     *     
     */
    public void setActual(JAXBElement<Actual> value) {
        this.actual = value;
    }

    /**
     * Gets the value of the stated property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Stated }{@code >}
     *     
     */
    public JAXBElement<Stated> getStated() {
        return stated;
    }

    /**
     * Sets the value of the stated property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Stated }{@code >}
     *     
     */
    public void setStated(JAXBElement<Stated> value) {
        this.stated = value;
    }

}
