//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.08 at 09:34:59 AM EST 
//


package com.liconic.binding.sys;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="device" type="{http://com.liconic.sys}device" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="labware" type="{http://com.liconic.sys}labware" minOccurs="0"/>
 *         &lt;element name="cmds" type="{http://com.liconic.sys}cmds" minOccurs="0"/>
 *         &lt;element name="sysId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="sysName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="scheduler" type="{http://com.liconic.sys}scheduler" minOccurs="0"/>
 *         &lt;element name="jobs" type="{http://com.liconic.sys}jobs" minOccurs="0"/>
 *         &lt;element name="plates" type="{http://com.liconic.sys}plates" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "device",
    "labware",
    "cmds",
    "sysId",
    "sysName",
    "scheduler",
    "jobs",
    "plates"
})
@XmlRootElement(name = "sys")
public class Sys {

    @XmlElement(nillable = true)
    protected List<Device> device;
    @XmlElementRef(name = "labware", namespace = "http://com.liconic.sys", type = JAXBElement.class, required = false)
    protected JAXBElement<Labware> labware;
    @XmlElementRef(name = "cmds", namespace = "http://com.liconic.sys", type = JAXBElement.class, required = false)
    protected JAXBElement<Cmds> cmds;
    @XmlElementRef(name = "sysId", namespace = "http://com.liconic.sys", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> sysId;
    @XmlElementRef(name = "sysName", namespace = "http://com.liconic.sys", type = JAXBElement.class, required = false)
    protected JAXBElement<String> sysName;
    @XmlElementRef(name = "scheduler", namespace = "http://com.liconic.sys", type = JAXBElement.class, required = false)
    protected JAXBElement<Scheduler> scheduler;
    @XmlElementRef(name = "jobs", namespace = "http://com.liconic.sys", type = JAXBElement.class, required = false)
    protected JAXBElement<Jobs> jobs;
    @XmlElementRef(name = "plates", namespace = "http://com.liconic.sys", type = JAXBElement.class, required = false)
    protected JAXBElement<Plates> plates;

    /**
     * Gets the value of the device property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the device property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDevice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Device }
     * 
     * 
     */
    public List<Device> getDevice() {
        if (device == null) {
            device = new ArrayList<Device>();
        }
        return this.device;
    }

    /**
     * Gets the value of the labware property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Labware }{@code >}
     *     
     */
    public JAXBElement<Labware> getLabware() {
        return labware;
    }

    /**
     * Sets the value of the labware property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Labware }{@code >}
     *     
     */
    public void setLabware(JAXBElement<Labware> value) {
        this.labware = value;
    }

    /**
     * Gets the value of the cmds property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Cmds }{@code >}
     *     
     */
    public JAXBElement<Cmds> getCmds() {
        return cmds;
    }

    /**
     * Sets the value of the cmds property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Cmds }{@code >}
     *     
     */
    public void setCmds(JAXBElement<Cmds> value) {
        this.cmds = value;
    }

    /**
     * Gets the value of the sysId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getSysId() {
        return sysId;
    }

    /**
     * Sets the value of the sysId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setSysId(JAXBElement<Integer> value) {
        this.sysId = value;
    }

    /**
     * Gets the value of the sysName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSysName() {
        return sysName;
    }

    /**
     * Sets the value of the sysName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSysName(JAXBElement<String> value) {
        this.sysName = value;
    }

    /**
     * Gets the value of the scheduler property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Scheduler }{@code >}
     *     
     */
    public JAXBElement<Scheduler> getScheduler() {
        return scheduler;
    }

    /**
     * Sets the value of the scheduler property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Scheduler }{@code >}
     *     
     */
    public void setScheduler(JAXBElement<Scheduler> value) {
        this.scheduler = value;
    }

    /**
     * Gets the value of the jobs property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Jobs }{@code >}
     *     
     */
    public JAXBElement<Jobs> getJobs() {
        return jobs;
    }

    /**
     * Sets the value of the jobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Jobs }{@code >}
     *     
     */
    public void setJobs(JAXBElement<Jobs> value) {
        this.jobs = value;
    }

    /**
     * Gets the value of the plates property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Plates }{@code >}
     *     
     */
    public JAXBElement<Plates> getPlates() {
        return plates;
    }

    /**
     * Sets the value of the plates property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Plates }{@code >}
     *     
     */
    public void setPlates(JAXBElement<Plates> value) {
        this.plates = value;
    }

}
