//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.08 at 09:34:59 AM EST 
//


package com.liconic.binding.sys;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for task complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="task">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="props" type="{http://com.liconic.sys}property" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="stats" type="{http://com.liconic.sys}tstatus" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="commands" type="{http://com.liconic.sys}cmds" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="info" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cstat" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="run" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="step" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="errinfo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "task", propOrder = {
    "props",
    "stats",
    "commands"
})
public class Task {

    @XmlElement(nillable = true)
    protected List<Property> props;
    @XmlElement(nillable = true)
    protected List<Tstatus> stats;
    @XmlElementRef(name = "commands", namespace = "http://com.liconic.sys", type = JAXBElement.class, required = false)
    protected JAXBElement<Cmds> commands;
    @XmlAttribute(name = "id")
    protected Integer id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "info")
    protected String info;
    @XmlAttribute(name = "title")
    protected String title;
    @XmlAttribute(name = "cstat")
    protected String cstat;
    @XmlAttribute(name = "run")
    protected Integer run;
    @XmlAttribute(name = "step")
    protected String step;
    @XmlAttribute(name = "errinfo")
    protected String errinfo;

    /**
     * Gets the value of the props property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the props property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProps().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     * 
     * 
     */
    public List<Property> getProps() {
        if (props == null) {
            props = new ArrayList<Property>();
        }
        return this.props;
    }

    /**
     * Gets the value of the stats property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stats property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStats().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tstatus }
     * 
     * 
     */
    public List<Tstatus> getStats() {
        if (stats == null) {
            stats = new ArrayList<Tstatus>();
        }
        return this.stats;
    }

    /**
     * Gets the value of the commands property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Cmds }{@code >}
     *     
     */
    public JAXBElement<Cmds> getCommands() {
        return commands;
    }

    /**
     * Sets the value of the commands property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Cmds }{@code >}
     *     
     */
    public void setCommands(JAXBElement<Cmds> value) {
        this.commands = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the info property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfo() {
        return info;
    }

    /**
     * Sets the value of the info property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfo(String value) {
        this.info = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the cstat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCstat() {
        return cstat;
    }

    /**
     * Sets the value of the cstat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCstat(String value) {
        this.cstat = value;
    }

    /**
     * Gets the value of the run property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRun() {
        return run;
    }

    /**
     * Sets the value of the run property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRun(Integer value) {
        this.run = value;
    }

    /**
     * Gets the value of the step property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStep() {
        return step;
    }

    /**
     * Sets the value of the step property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStep(String value) {
        this.step = value;
    }

    /**
     * Gets the value of the errinfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrinfo() {
        return errinfo;
    }

    /**
     * Sets the value of the errinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrinfo(String value) {
        this.errinfo = value;
    }

}
